config/routes.rb
Interactivehomedevicecontroller::Application.routes.draw do
  resources :devices do
    get 'power'
    resources :options
  end

  root :to => 'devices#index'

  match ':controller(/:action(/:id(.:format)))'
end

app/models/device.rb
class Device < ActiveRecord::Base

  validates_presence_of :name, :location, :device_type

  def to_json
    options[:only] = [:id, :name, :location, :power, :type]
    super(options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  inherit_resources
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  respond_to :html, :xml, :json, :js
  actions :index, :show, :new, :create, :edit, :destroy, :update

  def index
    @devices = Device.all #paginate :page => params[:page], :per_page => 5, :order => 'created_at DESC' 

    index!
  end

  def power
    @device = Device.find(params[:device_id])
    @device.power = (@device.power ? false : true)
    @device.save!
    render :show
  end
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  belongs_to :device
  respond_to :html, :xml, :json, :js
  actions :show, :new, :create, :edit, :index

  def new
    @device = Device.find(params[:device_id])
    new!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def power_switch(boolean)
    boolean ? 'on' : 'off'
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_device.html.haml
= content_tag_for :div, device do
  %ul.device-attributes
    %li
      %strong Name:
      =h device.name
    %li
      %strong Location:
      =h device.location
    %li
      %strong Power:
      =h power_switch device.power
    %li
      %strong DeviceType:
      =h device.device_type
      
  %ul.device-actions
    %li
      = link_to 'Show', device
    %li
      = link_to 'Edit', edit_device_path(device)
    %li
      = link_to 'Destroy', device, :confirm => 'Are you sure?', :method => :delete

app/views/devices/_form.html.haml
= form.inputs do
  = form.input :name, :label => 'Name'
  = form.input :location, :label => 'Location'
  = form.input :device_type, :label => 'DeviceTypes'#, :collection => ['Beleuchtung']
  = form.input :power, :label => 'Power'
= form.buttons :commit

app/views/devices/edit.html.haml
%h2 Editing device
= semantic_form_for @device do |form|
  = render :partial => "form", :locals => {:form => form}

= link_to 'test', new_device_option_path(@device), :remote => true
%ul.device-actions
  %li= link_to 'Show', @device
  %li= link_to 'Back', devices_path
  %li= link_to 'Destroy', @device, :confirm => 'Are you sure?', :method => :delete

app/views/devices/index.html.haml
%h2 Listing devices
- if !@devices.empty?
  .devices
    = render :partial => "device", :collection => @devices
  =# will_paginate @devices
- else
  %p There are no devices to show yet.
%ul.device-actions
  %li
    = link_to 'New device', new_device_url

app/views/devices/new.html.haml
%h2 New device
= semantic_form_for @device do |form|
  = render :partial => 'form', :locals => {:form => form}
%ul.device-actions
  %li= link_to 'Back', devices_path

app/views/devices/show.html.haml
%h2
  = "Device: #{@device.name}"
- content_tag_for :div, @device do
  %ul.device-attributes
    %li
      %strong Name:
      =h @device.name
    %li
      %strong Location:
      =h @device.location
    %li
      %strong DeviceType
      =h @device.device_type
    %li
      %strong Power:
      =h power_switch @device.power

%ul.device-actions
  %li= link_to 'Edit', edit_device_path(@device)
  %li= link_to 'Back', devices_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Interactive home device controller
    = csrf_meta_tag
    = stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
    = stylesheet_link_tag 'compiled/print.css', :media => 'print'
    /[if IE]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
  %body{:id => controller_name}
    #container
      #qr-code
        = image_tag 'rest_access_apk.png'
      #content
        = yield
    = javascript_include_tag :defaults

app/views/options/_form.html.haml
= form.inputs do
  = form.input :name
  = form.buttons :commit

app/views/options/_new.html.haml
%li
  New Option:
= render :partial => 'options/form', :locals => {:form => form}

app/views/options/_option.html.haml
%li
  %strong name
  = option.name

app/views/options/new.html.haml
%h2 New option
= semantic_form_for @option do |form|
  = render :partial => 'form', :locals => {:form => form}
%ul.device-actions
  %li= link_to 'Back', devices_path